//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ai2dShooter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ai2dShooter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theodore
        ///Robt
        ///Herschel
        ///Otto
        ///Burt
        ///Jeremy
        ///Myles
        ///Fernando
        ///Dennis
        ///Lynn
        ///Rich
        ///Larry
        ///Jarrett
        ///Mckinley
        ///Dino
        ///Kelly
        ///Jon
        ///Werner
        ///Will
        ///Julian
        ///Franklyn
        ///Rubin
        ///Pedro
        ///Reuben
        ///Sam
        ///Jame
        ///Gaston
        ///Brendan
        ///Teodoro
        ///Chas
        ///Brock
        ///Trent
        ///Williams
        ///Andrew
        ///Stanley
        ///Warren
        ///Denny
        ///Robin
        ///Rolf
        ///Mitch
        ///Lavern
        ///Brandon
        ///Theo
        ///Matt
        ///Jeremiah
        ///Carlton
        ///Alexis
        ///Maynard
        ///Ellsworth
        ///Omar
        ///Tashina
        ///Vi
        ///Amanda
        ///Alysa
        ///Isa
        ///Shaunta
        ///Latarsha
        ///Glennis
        ///Lu
        ///Venus
        ///Nguyet
        ///Shenna
        ///Melani
        ///Haley
        ///Sirena
        ///Lovie
        ///Lilly
        ///Julie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
    }
}
